### PR TITLE
Add bors tool

### PR DESCRIPTION
**Pull request by alallema**

### CODE REVIEW

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
Is it possible to add the badge on the readme:
<a href="https://app.bors.tech/repositories/34948">Bors enabled</a>

**Comment by curquiza** [comment]
I changed the acces: only you and me (because I can't remove myself) can `bors merge`

**Review by curquiza — APPROVED** [review]
🎉

**Comment by alallema** [comment]
bors merge

**Comment by curquiza** [comment]
Weird:

Capture d’écran 2021-07-26 à 14 45 21

**Comment by alallema** [comment]
bors retry

**Comment by curquiza** [comment]
It should be ok now :)

**Pull request merged**
