### PR TITLE
Add pylint

### PR DESCRIPTION
**Pull request by nicolasvienot**
This is the first draft about adding pylint to this repository.

What has been done :

- Add pylint in the requirements
- Update cryptography
- Add pylintrc using the one in meilisearch-python
- Add a github action to test with pylint on push and pr
- Format using autopep8
- Fix most of the errors raised by pylint

This is what's left to be fixed :
```
************* Module tools.create_droplet
tools/create_droplet.py:11:0: C0103: Constant name "logger" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
tools/create_droplet.py:14:97: W0621: Redefining name 'logger' from outer scope (line 11) (redefined-outer-name)
tools/create_droplet.py:18:11: W0703: Catching too general exception Exception (broad-except)
tools/create_droplet.py:43:75: W0621: Redefining name 'logger' from outer scope (line 11) (redefined-outer-name)
tools/create_droplet.py:43:0: R0914: Too many local variables (36/25) (too-many-locals)
tools/create_droplet.py:54:4: C0103: Variable name "DIGITALOCEAN_ACCESS_TOKEN" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:56:4: C0103: Variable name "CLOUDFLARE_API_KEY" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:57:4: C0103: Variable name "CLOUDFLARE_EMAIL" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:58:4: C0103: Variable name "CLOUDFLARE_ZONE" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:62:4: C0103: Variable name "MEILI_VERSION" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:63:4: C0103: Variable name "MEILI_IMG_SLUG" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:68:4: C0103: Variable name "SIZE_SLUG" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:69:4: C0103: Variable name "DROPLET_NAME" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:70:4: C0103: Variable name "DROPLET_TAGS" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:71:4: C0103: Variable name "SSH_KEYS_FINGERPRINTS" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:75:4: C0103: Variable name "ENABLE_BACKUPS" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:85:4: C0103: Variable name "USE_API_KEY" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:86:4: C0103: Variable name "MEILISEARCH_API_KEY" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:87:4: C0103: Variable name "USE_SSL" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:88:4: C0103: Variable name "USE_CERTBOT" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:89:4: C0103: Variable name "DOMAIN_NAME" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:124:4: C0103: Variable name "USER_DATA" doesn't conform to '[a-z_][a-z0-9_]{2,30}$' pattern (invalid-name)
tools/create_droplet.py:159:16: E1101: Instance of 'CloudFlare' has no 'zones' member (no-member)
************* Module tools.do_meili_tools
tools/do_meili_tools.py:23:15: W0703: Catching too general exception Exception (broad-except)
tools/do_meili_tools.py:34:15: W0703: Catching too general exception Exception (broad-except)
tools/do_meili_tools.py:45:15: W0703: Catching too general exception Exception (broad-except)
tools/do_meili_tools.py:61:15: W0703: Catching too general exception Exception (broad-except)
************* Module tools.build_image
tools/build_image.py:74:4: C0103: Constant name "ssh_command" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)

------------------------------------------------------------------
Your code has been rated at 8.23/10 (previous run: 8.23/10, +0.00)
```

### CODE REVIEW

**Review by eskombro — CHANGES_REQUESTED** [review]
Thanks a lot for these additions! These scripts needed a little loving care (and cleaning) 🎉 

Is it possible to rename `do_meili_tools.py` to `utils.py` (and relink the modules) to have the same structure as in the other repos? :)

Also, I don't know if we want to keep all the comments, doc, and unused values on `.pylintrc`. It feels quite polluted, but the information is quite useful for someone who is making modifications for contributors, etc... WDYT?

Finally, GJ for the CI! Now we will need to make it 10/10 to be able to merge this PR 😂 

I will fix the last problems with pylint and push a commit on this same branch if you are OK with that 👌🏽

**Comment by eskombro** [comment]
Closes #98

**Comment by nicolasvienot** [comment]
> Is it possible to rename do_meili_tools.py to utils.py (and relink the modules) to have the same structure as in the other repos? :)

Yes, I'll do that 👍 

> Also, I don't know if we want to keep all the comments, doc, and unused values on .pylintrc. It feels quite polluted, but the information is quite useful for someone who is making modifications for contributors, etc... WDYT?

I believe we could clean it a bit, in order to make it readable and remove unused values, I'll do that when we are done configurating it (I'm thinking maybe number of locals for funtions and regex for constants/variables naming)

> I will fix the last problems with pylint and push a commit on this same branch if you are OK with that 👌🏽

If you could that would be nice, as it will serve as an example (from the cloud scripts father) for me to do the same in the other repositories.

🎉🎉🎉

**Comment by eskombro** [comment]
I almost forgot: we need to document that on the CONTRIBUTING.md. For this, the best inspiration will probably be the [meilisearch-python CONTRIBUTING](https://github.com/meilisearch/meilisearch-python/blob/main/CONTRIBUTING.md#tests-and-linter-)

**Comment by nicolasvienot** [comment]
Hey @eskombro 😊

I updated this branch with a few modifications.

- I renamed the  `do_meili_tools.py` to `utils.py` and fixed the modules
- I added a `config.py` that will contain all the constants for the `build_image.py` (as in the other cloud repos)
- I updated the `CONTRIBUTING.md`, adding a Development Workflow and the linter commandes. I also changed a bit the release process as the files name changed.

I had an issue testing the build_image process, following the contributing.md and release steps :
On step `# Execute deploy script via SSH` in the python script, I had some permission denied, which resulted in the commands not being applied but the snapshot being created. I added this issue in #145.

I suspected it might come from the `SSH_KEYS_FINGERPRINTS` not being updated for me?
So I changed those with my public key, and then it would run smoothly except for one thing, I have one test that doen't pass in the `img_check.sh` script from digitalocean. You'll find the output below. Maybe the script applied after fixed that (`cleanup.sh`), but please confirm. Also if that's the case, might be a good idea to change the order 😁
 
```Checking user: meilisearch...
[PASS] User meilisearch has no password set.
[ OK ] User meilisearch has no SSH keys present
Checking the root account...
[PASS] User root has no password set.
[FAIL] User root has a populated authorized_keys file in /root/.ssh/authorized_keys
File Contents:
ssh-rsa <my publickey>
--------------
[PASS] The Root User's Bash History is not present
[PASS] DigitalOcean Monitoring agent was not found
[PASS] MongoDB is not installed
---------------------------------------------------------------------------------------------------
Scan Complete. 
One or more tests failed.  Please review these items and re-test.
---------------------------------------------------------------------------------------------------
9 Tests PASSED
0 WARNINGS
1 Tests FAILED
---------------------------------------------------------------------------------------------------
Some critical tests failed.  These items must be resolved and this scan re-run before you submit your image to the DigitalOcean Marketplace.```

**Comment by nicolasvienot** [comment]
About the no-member errors raised by pylint, there is options to put in the pylintrc file :
`generated-members` or `ignored-module`
See https://docs.pylint.org/en/1.6.0/features.html

**Review by eskombro — COMMENTED** [review]
@nicolasvienot 

> I had an issue testing the build_image process, following the contributing.md and release steps :
> On step `# Execute deploy script via SSH` in the python script, I had some permission denied, which resulted in the commands not being applied but the snapshot being created. I added this issue in #145.
> 
> I suspected it might come from the `SSH_KEYS_FINGERPRINTS` not being updated for me?

It is indeed something that I may have missed while doing the contributing: the SSH key fingerprint should correspond to the SSH key the user added to DigitalOcean from his own machine! If the value is not set to the one corresponding to your own key, you won't have SSH access (And nor will the script). 

> I have one test that doesn't pass in the `img_check.sh` script from digitalocean. You'll find the output below. Maybe the script applied after fixed that (`cleanup.sh`), but please confirm. Also if that's the case, might be a good idea to change the order 😁

The order in which these scripts are executed (`img_check.sh` and `cleanup.sh`) can not just be changed: the `cleanup.sh` script will remove your SSH key! So this has to be the last command. If you try to run the `img_check.sh` afterward via SSH, this will of course fail. So as for now, having 1 fail on the `img_check.sh` corresponding to the SSH key present for the root user is OK, since right after this we are doing the cleanup. If you have another idea on how to run it, we can of course discuss it. :)

**Review by eskombro — COMMENTED** [review]
I don't think the `--rcfile=.pylintrc` is needed, as it will use this file by default [as stated here](https://docs.pylint.org/en/1.6.0/run.html)

```
Specifying all the options suitable for your setup and coding standards can be tedious, so it is possible to use a configuration file to specify the default values. You can specify a configuration file on the command line using the --rcfile option. Otherwise, Pylint searches for a configuration file in the following order and uses the first one it finds:

    1. pylintrc in the current working directory
    2. .pylintrc in the current working directory
    3. If the current working directory is in a Python module, Pylint searches up the hierarchy of Python modules until it finds a pylintrc file. This allows you to specify coding standards on a module-by-module basis. Of course, a directory is judged to be a Python module if it contains an __init__.py file.
    4. The file named by environment variable PYLINTRC
    5. if you have a home directory which isn’t /root:
        1. .pylintrc in your home directory
        2. .config/pylintrc in your home directory
    6. /etc/pylintrc

```

**Comment by eskombro** [comment]
> About the no-member errors raised by pylint, there is options to put in the pylintrc file :
> `generated-members` or `ignored-module`
> See https://docs.pylint.org/en/1.6.0/features.html

Instead of disabling the rule, I just added an exception to this specific class, since this attribute is apparently created dynamically

I also disabled the check for `W0703: Catching too general exception Exception (broad-except)`. These are indeed intentionally broad excepts because trying to catch every specific exception that could come up in the image build is not necessary. These try/except are just there to avoid problems trying to reach the machine while it is being created or unavailable (health check on a machine while it is being created for example, which could raise an Exception) inside the `wait_for...` methods.

**Comment by nicolasvienot** [comment]
> The order in which these scripts are executed (img_check.sh and cleanup.sh) can not just be changed: the cleanup.sh script will remove your SSH key! So this has to be the last command. If you try to run the img_check.sh afterward via SSH, this will fail. So as for now, having 1 fail on the img_check.sh corresponding to the SSH key present for the root user is OK, since right after this we are doing the cleanup. If you have another idea on how to run it, we can of course discuss it. :)

This makes sense, and yes you're right we can't reverse them. It's just a bit annoying to me that we can't use this test as a final checker, stopping the process if we get an error for example. We still have to read the output to know if there might be another error than the ssh key. Anyway, this is far from the pylint scope, let me know if you think we should add it as a potential issue. I think that there is a few places where the script should stop and not create the snapshot.

**Review by eskombro — APPROVED** [review]
🎉

**Pull request merged**
