### PR TITLE
Create a script to test the image built and add the full process to CI

### LINKED ISSUE #88: Create test-image script
- Create a Droplet based on a specific MeiliSearch image [snapshot created with build-image.sh script]
- GET `/health/`
- GET `/version` and compare to the current version
- Test environment is correct if necessary
- Delete Droplet

### PR DESCRIPTION
**Pull request by nicolasvienot**
closes #88 and #89 

- Add `test_image.py` to be used with the snapshot name as arg
- Add `destroy_image.py` to be used with the snapshot name as arg
- We can now optionnaly use `build_image.py` with an argument corresponding to the snapshot name
- Add version check in build_image.py and test_image.py
- Add github action to run the test : build an image, test it and create a snapshot from it, test this snapshot by creating an image with it, destroy everything
- Add timeout for healthcheck

### CODE REVIEW

**Comment by nicolasvienot** [comment]
- The first try on the github action CI failed on the `Build Image` step
Seeing the logs, it looks like it failed on the version-check in `build_image.py`
`Waiting for Version check
   Exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`
It took more than 30 minutes which is not normal, and shouldn't fail there. (Got timedout)

- Second try (no changes) went well but took too long (~25min)

**Comment by nicolasvienot** [comment]
Clue about the potential error/long run :

`2021-03-30T17:47:28.5510968Z Powering down droplet...
2021-03-30T17:47:28.5513700Z    Exception: HTTPSConnectionPool(host='api.digitalocean.com', port=443): Read timed out. (read timeout=None)
2021-03-30T17:47:28.5515311Z    Droplet is OFF`

Happening when we `wait_for_droplet_shutdown`

**Comment by nicolasvienot** [comment]
> Happening when we shudown or wait_for_droplet_shutdown

This is now happening sometimes in `take_snapshot()` from `build_image.py`

-> Usually only on `build_image.py`, even if `test_image.py`does pretty much the same thing but taking snapshot.
-> Never had a problem in own machine, or in ubuntu machine from digitalocean itself

Only solution found for now: Run the CI on `macos-latest`

**Review by eskombro — APPROVED** [review]
Amaaaaaaaaaaazing! <3

**Pull request merged**
