### PR TITLE
Try to fix CI on github action

### LINKED ISSUE #212: CI failed randomly on `Build_image`
**Description**
The CI failed during its automatic launch.

**Expected behavior**
Ci should pass every time

**Current behavior**
An error is raised [here an example on bump merge](https://github.com/meilisearch/meilisearch-digitalocean/runs/3130618318?check_suite_focus=true)

**Screenshots or Logs**
```
Run python3 tools/build_image.py $IMAGE_NAME
  python3 tools/build_image.py $IMAGE_NAME
  shell: /bin/bash -e {0}
  env:
    DIGITALOCEAN_ACCESS_TOKEN: 
    REQUEST_TIMEOUT_ENV_VAR: 30
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.7.11/x64
    IMAGE_NAME: meilisearch_digitalocean_ci_test_22-07-2021-04-16-02
Creating droplet...
Traceback (most recent call last):
  File "tools/build_image.py", line 20, in <module>
    droplet.create()
  File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/digitalocean/Droplet.py", line 568, in create
    data = self.get_data("droplets/", type=POST, params=data)
  File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/digitalocean/Droplet.py", line 165, in get_data
    data = super(Droplet, self).get_data(*args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/digitalocean/baseapi.py", line 216, in get_data
    req = self.__perform_request(url, type, params)
  File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/digitalocean/baseapi.py", line 92, in __perform_request
    raise TokenError("No token provided. Please use a valid token")
digitalocean.TokenError: No token provided. Please use a valid token
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by alallema**
Change v1 to v2 on GitHub action
closes #212 thanks to @sanders41

### CODE REVIEW

**Comment by curquiza** [comment]
I should update all our CIs with the last version of each GHA.
I put it on my TODO.

**Comment by alallema** [comment]
> I should update all our CIs with the last version of each GHA.
> I put it on my TODO.

Yes I just wanted to tell you that

**Comment by sanders41** [comment]
@curquiza in case you didn't already know and would find it helpful, dependabot can also keep Actions up to date. It just goes as a second `package-ecosystem` in your yaml file (example [here](https://github.com/sanders41/meilisearch-python-async/blob/main/.github/dependabot.yaml) for reference).

```yaml
- package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
```

**Comment by curquiza** [comment]
Oh my god, I did not know...!!! Thank you so much! I change the task on my TODO 🤓

**Review by eskombro — APPROVED** [review]
Simple and effective 🎉 

Are you sure this is tackling the issue?
It is a good addition in any case :)

**Comment by sanders41** [comment]
@eskombro It's just a guess at this point so I'm not 100% sure it will fix it. I figure it's something easy to try and at least rule out since there is a GHA bug report that seems to match this issue.

**Comment by eskombro** [comment]
Hopefully a good guess! But great to know that Dependabot can keep actions up-to-date, I didn't know this!

Thanks @sanders41 !

**Comment by alallema** [comment]
bors merge

**Comment by curquiza** [comment]
Bors merge

**Comment by curquiza** [comment]
bors merge-

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
