### PR TITLE
Add .editorconfig and format repo files

### LINKED ISSUE #96: Add editorconfig file
To unify the basic styling rules, please add an editorconfig file like those ones:
- https://github.com/meilisearch/meilisearch-kubernetes/blob/master/.editorconfig
- https://github.com/meilisearch/meilisearch-python/blob/master/.editorconfig

### PR DESCRIPTION
**Pull request by eskombro**
Closes #96

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
README.md and .gitignore needs to be updated.

(The files in `tools/` too, but your next PR will change everything so let's ignore them for the moment 😇)

**Comment by eskombro** [comment]
I'm planning to pass all the files under the .editorconfig, but just waiting for #93 to be merged, then format the whole repo :)

**Comment by curquiza** [comment]
Ok, so could you open another issue? I would rather not this to be forgotten even if it's not the change of the year. This problem is exactly the kind of stuff that is in the "easily forgotten" scope 😂

**Review by curquiza — APPROVED** [review]

**Comment by eskombro** [comment]
Oh I mean, as part of this same PR

**Comment by curquiza** [comment]
Cool! Merge when you are ok!

**Pull request merged**
